issue #3 - stop processing container if a backup LVM exists

diff --git a/templates/backup_client.j2 b/templates/backup_client.j2
--- a/templates/backup_client.j2
+++ b/templates/backup_client.j2
@@ -81,6 +81,11 @@ if [ "$(pct status {{ pvecfg.lcx_id }} | awk '{print $2}')" = "running" ]; then
 		echo "ERROR: snapshot vm-{{ pvecfg.lcx_id }}-backup_client_pve exists for {{ pvecfg.lcx_id }} $LCXHOSTNAME" >>"$LOGFILE"
 		EXITCODE=$((EXITCODE+11))
 		{% if backup_client_pve_lcx_exitonerror %}exit 11{% endif -%}
+	elif $(lvdisplay | grep 'LV Path' | grep -qe 'vm-{{ pvecfg.lcx_id }}-disk-[0-9]\+-backup_client_pve$'); then
+		lvdisplay | grep 'LV Path' | grep -e 'vm-{{ pvecfg.lcx_id }}-disk-[0-9]\+-backup_client_pve$' >>"$LOGFILE" 2>&1
+		echo "ERROR: found existing backup_client_pve LV for {{ pvecfg.lcx_id }} $LCXHOSTNAME" >>"$LOGFILE"
+		EXITCODE=$((EXITCODE+11))
+		{% if backup_client_pve_lcx_exitonerror %}exit 11{% endif -%}
 	else
 		{% for pctexec in pvecfg.lcx_commands | default([]) -%}
 		pct exec {{ pvecfg.lcx_id }} -- {{ pctexec }} >> "$LOGFILE" 2>&1
