exit early if snapshot exists

diff --git a/templates/backup_client.j2 b/templates/backup_client.j2
--- a/templates/backup_client.j2
+++ b/templates/backup_client.j2
@@ -63,6 +63,11 @@ declare -r VGNAME=$(pvesh get /storage/local-lvm --noheader --noborder | sed '/^
 LCXHOSTNAME=$(pct config {{ pvecfg.lcx_id }} | sed '/^hostname:/!d;s/^hostname: *//g')
 echo "start container {{ pvecfg.lcx_id }} $LCXHOSTNAME ..." >>"$LOGFILE"
 if [ "$(pct status {{ pvecfg.lcx_id }} | awk '{print $2}')" = "running" ]; then
+	ROOTFS=$(pct config {{ pvecfg.lcx_id }} | sed '/^rootfs: local-lvm:/!d;s/^rootfs: *local-lvm://g;s/,.*$//g')
+	if $(pct listsnapshot {{ pvecfg.lcx_id }} | grep  -q "\-> vm-{{ pvecfg.lcx_id }}-backup_client_pve "); then
+		echo "ERROR: snapshot vm-{{ pvecfg.lcx_id }}-backup_client_pve exists for {{ pvecfg.lcx_id }} $LCXHOSTNAME" >>"$LOGFILE"
+		exit 11
+	fi
 {% for pctexec in pvecfg.lcx_commands | default([]) %}
 	pct exec {{ pvecfg.lcx_id }} -- {{ pctexec }} >> "$LOGFILE" 2>&1
 	EXITCODE=$((EXITCODE+$?))
@@ -81,11 +86,6 @@ if [ "$(pct status {{ pvecfg.lcx_id }} | awk '{print $2}')" = "running" ]; then
 	set -e
 	# for now, we just support local-lvm
 	mkdir -p {{ backup_client_pve_mountpoint }}/${LCXHOSTNAME}/ >>"$LOGFILE" 2>&1
-	ROOTFS=$(pct config {{ pvecfg.lcx_id }} | sed '/^rootfs: local-lvm:/!d;s/^rootfs: *local-lvm://g;s/,.*$//g')
-	if $(pct listsnapshot {{ pvecfg.lcx_id }} | grep  -q "\-> vm-{{ pvecfg.lcx_id }}-backup_client_pve "); then
-		echo "ERROR: snapshot vm-{{ pvecfg.lcx_id }}-backup_client_pve exists for {{ pvecfg.lcx_id }} $LCXHOSTNAME" >>"$LOGFILE"
-		exit 11
-	fi
 	lvcreate -ay -Ky -n ${ROOTFS}-backup_client_pve -s /dev/${VGNAME}/$ROOTFS >>"$LOGFILE" 2>&1
 	mount -o ro /dev/${VGNAME}/${ROOTFS}-backup_client_pve {{ backup_client_pve_mountpoint }}/${LCXHOSTNAME}/ >>"$LOGFILE" 2>&1
 	while read d m; do
